In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('pic.jpg', cv2.IMREAD_COLOR)

In [7]:
cv2.line(img, (0,0), (150,150), (0,0,0), 15)

cv2.rectangle(img, (15,25), (200,150), (0,255,0), 5)

cv2.circle(img, (100, 100), 55, (0,0,255), -1)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 67,  58,  55],
        [ 82,  73,  70],
        [ 78,  69,  66]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 72,  63,  60],
        [ 76,  67,  64],
        [ 80,  71,  68]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 79,  70,  67],
        [ 73,  64,  61],
        [ 84,  75,  72]],

       ...,

       [[201, 196, 195],
        [188, 183, 182],
        [173, 168, 167],
        ...,
        [219, 215, 214],
        [221, 217, 216],
        [221, 217, 216]],

       [[201, 196, 195],
        [181, 176, 175],
        [163, 158, 157],
        ...,
        [218, 214, 213],
        [219, 215, 214],
        [219, 215, 214]],

       [[196, 190, 191],
        [174, 168, 169],
        [162, 156, 157],
        ...,
        [220, 218, 218],
        [219, 217, 217],
        [218, 216, 216]]

In [11]:
pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
pts = pts.reshape((-1,1,2))
cv2.polylines(img, [pts], True, (0,255,255), 3)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 67,  58,  55],
        [ 82,  73,  70],
        [ 78,  69,  66]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 72,  63,  60],
        [ 76,  67,  64],
        [ 80,  71,  68]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 79,  70,  67],
        [ 73,  64,  61],
        [ 84,  75,  72]],

       ...,

       [[201, 196, 195],
        [188, 183, 182],
        [173, 168, 167],
        ...,
        [219, 215, 214],
        [221, 217, 216],
        [221, 217, 216]],

       [[201, 196, 195],
        [181, 176, 175],
        [163, 158, 157],
        ...,
        [218, 214, 213],
        [219, 215, 214],
        [219, 215, 214]],

       [[196, 190, 191],
        [174, 168, 169],
        [162, 156, 157],
        ...,
        [220, 218, 218],
        [219, 217, 217],
        [218, 216, 216]]

In [15]:
font = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(img, 'Hello World', (0,130), font, 1, (200,255,255), 2, cv2.LINE_AA)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 67,  58,  55],
        [ 82,  73,  70],
        [ 78,  69,  66]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 72,  63,  60],
        [ 76,  67,  64],
        [ 80,  71,  68]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 79,  70,  67],
        [ 73,  64,  61],
        [ 84,  75,  72]],

       ...,

       [[201, 196, 195],
        [188, 183, 182],
        [173, 168, 167],
        ...,
        [219, 215, 214],
        [221, 217, 216],
        [221, 217, 216]],

       [[201, 196, 195],
        [181, 176, 175],
        [163, 158, 157],
        ...,
        [218, 214, 213],
        [219, 215, 214],
        [219, 215, 214]],

       [[196, 190, 191],
        [174, 168, 169],
        [162, 156, 157],
        ...,
        [220, 218, 218],
        [219, 217, 217],
        [218, 216, 216]]

In [16]:
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1