In [1]:
import numpy as np

### ufuncs

In [4]:
a = [1,2,3,4,5]
a = np.array(a)

In [5]:
b = a + 5
b

array([ 6,  7,  8,  9, 10])

In [6]:
b = a * 5
b

array([ 5, 10, 15, 20, 25])

In [7]:
b = a ** 2
b

array([ 1,  4,  9, 16, 25])

In [12]:
b = a | 1
b

array([1, 3, 3, 5, 5])

In [23]:
a = [1,2,3,4,5,6]
a = np.array(a)
b = a > 3
b

array([False, False, False,  True,  True,  True])

In [24]:
c = a[b] * 2
c

array([ 8, 10, 12])

In [25]:
c.min()

8

In [30]:
x = np.random.random((10,3))
x

array([[0.76961021, 0.26508859, 0.83734238],
       [0.34209377, 0.67164852, 0.03775931],
       [0.03065433, 0.55195672, 0.65911293],
       [0.35660166, 0.29187151, 0.37640799],
       [0.37549759, 0.69143521, 0.81900904],
       [0.41078385, 0.67355325, 0.45404885],
       [0.96494707, 0.53310686, 0.80621399],
       [0.81520317, 0.074378  , 0.59006216],
       [0.01576811, 0.1942551 , 0.72327255],
       [0.44591557, 0.87222024, 0.41426716]])

In [45]:
diff = x.reshape(10,1,3) - x
D = (diff**2).sum(2)

In [47]:
i = np.arange(10)
D[i,i] = np.inf

In [49]:
i = np.argmin(D, 1)

In [50]:
i

array([7, 5, 8, 5, 5, 9, 0, 0, 2, 5])